name: PrimeNumberCalculator-Unit-Test

on:
  push:
    branches: [ master ]
  
jobs:
  execute-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with: 
          node-version: 14.16.0
      - name: Install dependencies
        run: npm install
      - name: Running unit tests
        run: npm test PrimeNumberCalculatorMochaTest.js
